name: Update variable JSON

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Value to publish"
        required: true
        type: string
      by:
        description: "Sender (optional)"
        required: false
        type: string
      ts:
        description: "Timestamp ISO (optional)"
        required: false
        type: string

jobs:
  write:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow commit with GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make docs folder
        run: mkdir -p docs

      - name: Write JSON
        run: |
          VALUE=${{ github.event.inputs.value }}
          BY=${{ github.event.inputs.by }}
          TS=${{ github.event.inputs.ts }}
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          cat > docs/data.json << 'JSON'
          {
            "value": "__VALUE__",
            "updated_at": "__UPDATED__",
            "by": "__BY__"
          }
          JSON

          # fill placeholders safely
          sed -i "s|__VALUE__|$(printf '%s' "$VALUE" | sed 's/[&/\]/\\&/g')|" docs/data.json
          sed -i "s|__UPDATED__|${TS:-$NOW}|" docs/data.json
          sed -i "s|__BY__|$(printf '%s' "$BY" | sed 's/[&/\]/\\&/g')|" docs/data.json

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data.json
          git commit -m "update: ${{ github.event.inputs.value }}"
          git push
