name: Update Gist data.json

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Value to write into the gist"
        required: true
        type: string

jobs:
  update-gist:
    runs-on: ubuntu-latest
    
    env:
      GIST_ID: cd788f03a1d8c9a14a2f917ab71b7f43
      FILE_NAME: data.json
    
    steps:
      - name: Build JSON payload
        run: |
          NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "{\"value\":\"${{ github.event.inputs.value }}\",\"updated_at\":\"$NOW\"}" > payload.json
          cat payload.json
      
      - name: Patch gist via API
        run: |
          CONTENT=$(cat payload.json)
          curl -sS -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/$GIST_ID \
            -d "{\"files\": {\"$FILE_NAME\": {\"content\": $(echo "$CONTENT" | jq -R .)}}}"
